import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { renderFlow, type FlowSpec } from '@flowink/core';

/**
 * Standalone Angular component rendering a FlowInk diagram.
 *
 * The SVG markup is generated by the core renderer and injected via
 * [innerHTML] after sanitization bypass - the markup is produced entirely
 * by this library from XML-escaped spec text, so it contains no scripts,
 * no external references, and no SMIL. OnPush keeps re-renders to spec
 * changes only.
 */
@Component({
  selector: 'flowink-diagram',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div role="img" [attr.aria-label]="spec?.title ?? 'flow diagram'" [innerHTML]="html"></div>`,
})
export class FlowDiagramComponent {
  private _spec: FlowSpec | null = null;

  @Input()
  set spec(value: FlowSpec | null) {
    this._spec = value;
    this.html = value
      ? this.sanitizer.bypassSecurityTrustHtml(renderFlow(value))
      : '';
  }

  get spec(): FlowSpec | null {
    return this._spec;
  }

  html: SafeHtml = '';

  constructor(private readonly sanitizer: DomSanitizer) {}
}
